/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import Connect.luongNhanVienDao_119;
import Service.Service;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.nhanVien_312;

/**
 *
 * @author ASUS
 */
public class DieuChinhLuong extends javax.swing.JFrame {
    int selectedIndex;
    Service qlService;
    DefaultTableModel defaultTableModel;
    private List<nhanVien_312> ql;
    private DefaultTableModel model;
    nhanVien_312 nv;
    luongNhanVienDao_119 qlbd;
    /**
     * Creates new form DieuChỉnhLuong
     */
    public DieuChinhLuong() {
        initComponents();
        tb_Luong312.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tb_Luong312.getTableHeader().setOpaque(false);
        tb_Luong312.getTableHeader().setBackground(new Color(0, 139, 139));
        tb_Luong312.getTableHeader().setForeground(new Color(255,255,240));
        tb_Luong312.setRowHeight(25);
        model = (DefaultTableModel)tb_Luong312.getModel();
        showTable();
        qlbd = new luongNhanVienDao_119();
        getDataComboBox();
    }
    private void setTableData(List<nhanVien_312> ql){
        for (nhanVien_312 qly : ql){
            defaultTableModel.addRow(new Object[]{qly.getID(), qly.getName(), qly.getPosition(), qly.getEmail(), qly.getLuongcb(), qly.getLuongthuong(), qly.getLuongnhan()});
            
        }
    }
    private void getDataComboBox(){
        List<String> data = qlbd.getAllId();
        for(String s: data){
            cbo_id.addItem(s);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        formChinh_312 = new javax.swing.JPanel();
        formMin_312 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbo_ChucVu = new javax.swing.JComboBox<>();
        txt_LuongCoBan = new javax.swing.JTextField();
        txt_LuongThuong = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txt_Email = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txt_Name = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Luong312 = new javax.swing.JTable();
        cbo_id = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        chuaNhan312 = new javax.swing.JRadioButton();
        daNhan312 = new javax.swing.JRadioButton();
        Color_form312 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_Exit = new com.k33ptoo.components.KButton();
        btn_Del = new com.k33ptoo.components.KButton();
        btn_Edit = new com.k33ptoo.components.KButton();
        btn_search = new com.k33ptoo.components.KButton();
        jTextField_tk = new javax.swing.JTextField();
        btn_refresh = new com.k33ptoo.components.KButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        formChinh_312.setBackground(new java.awt.Color(51, 204, 255));
        formChinh_312.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formMin_312.setBackground(new java.awt.Color(255, 255, 255));
        formMin_312.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("ID:");
        formMin_312.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 35, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Họ tên:");
        formMin_312.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 72, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Chức vụ:");
        formMin_312.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 119, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Lương cơ bản:");
        formMin_312.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Email:");
        formMin_312.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Nhận Lương:");
        formMin_312.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        cbo_ChucVu.setBackground(new java.awt.Color(204, 255, 255));
        cbo_ChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".", "Trưởng phòng", "Nhân Viên", "Giám đốc", "Chủ tịch", " ", " ", " ", " " }));
        cbo_ChucVu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        formMin_312.add(cbo_ChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 114, 107, -1));

        txt_LuongCoBan.setBorder(null);
        formMin_312.add(txt_LuongCoBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 25, 130, 29));

        txt_LuongThuong.setBorder(null);
        formMin_312.add(txt_LuongThuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 72, 130, 20));
        formMin_312.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 191, 181, -1));

        txt_Email.setBorder(null);
        formMin_312.add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 156, 171, 24));
        formMin_312.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 56, 130, 10));
        formMin_312.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 94, 130, 10));

        txt_Name.setBorder(null);
        formMin_312.add(txt_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 72, 146, 20));
        formMin_312.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 94, 146, 10));

        tb_Luong312.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Họ tên", "Chức vụ", "Email", "Lương cơ bản", "Lương thưởng", "Lương được nhận", "Đã Nhận"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_Luong312.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tb_Luong312.setRowHeight(25);
        tb_Luong312.setSelectionBackground(new java.awt.Color(102, 204, 255));
        tb_Luong312.setShowVerticalLines(false);
        tb_Luong312.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tb_Luong312);

        formMin_312.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 211, 695, 153));

        cbo_id.setBackground(new java.awt.Color(204, 255, 255));
        cbo_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cbo_id.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbo_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_idActionPerformed(evt);
            }
        });
        formMin_312.add(cbo_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 30, 107, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Money Bag Pounds_100px.png"))); // NOI18N
        formMin_312.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Money Bag Pounds_100px.png"))); // NOI18N
        formMin_312.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Money Bag Pounds_100px.png"))); // NOI18N
        formMin_312.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Money Bag Pounds_100px.png"))); // NOI18N
        formMin_312.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Lương thưởng:");
        formMin_312.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 75, -1, -1));

        chuaNhan312.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(chuaNhan312);
        chuaNhan312.setText("Chưa Nhận");
        formMin_312.add(chuaNhan312, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        daNhan312.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(daNhan312);
        daNhan312.setText("Đã Nhận");
        daNhan312.setDoubleBuffered(true);
        formMin_312.add(daNhan312, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        formChinh_312.add(formMin_312, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 74, 750, 380));

        Color_form312.setkEndColor(new java.awt.Color(153, 255, 255));
        Color_form312.setkStartColor(new java.awt.Color(105, 48, 195));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EMPLOYEES SALARY");

        btn_Exit.setText("EXIT");
        btn_Exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Exit.setkBorderRadius(50);
        btn_Exit.setkEndColor(new java.awt.Color(204, 0, 204));
        btn_Exit.setkHoverEndColor(new java.awt.Color(204, 51, 255));
        btn_Exit.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_Exit.setkHoverStartColor(new java.awt.Color(51, 255, 255));
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });

        btn_Del.setText("DEL");
        btn_Del.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Del.setkBorderRadius(50);
        btn_Del.setkEndColor(new java.awt.Color(204, 0, 204));
        btn_Del.setkHoverEndColor(new java.awt.Color(204, 51, 255));
        btn_Del.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_Del.setkHoverStartColor(new java.awt.Color(51, 255, 255));
        btn_Del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DelActionPerformed(evt);
            }
        });

        btn_Edit.setText("EDIT");
        btn_Edit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Edit.setkBorderRadius(50);
        btn_Edit.setkEndColor(new java.awt.Color(204, 0, 204));
        btn_Edit.setkHoverEndColor(new java.awt.Color(204, 51, 255));
        btn_Edit.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_Edit.setkHoverStartColor(new java.awt.Color(51, 255, 255));
        btn_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditActionPerformed(evt);
            }
        });

        btn_search.setText("SEARCH");
        btn_search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_search.setkBorderRadius(50);
        btn_search.setkEndColor(new java.awt.Color(204, 0, 204));
        btn_search.setkHoverEndColor(new java.awt.Color(204, 51, 255));
        btn_search.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_search.setkHoverStartColor(new java.awt.Color(51, 255, 255));
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        jTextField_tk.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField_tkCaretUpdate(evt);
            }
        });
        jTextField_tk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_tkMouseClicked(evt);
            }
        });
        jTextField_tk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_tkActionPerformed(evt);
            }
        });

        btn_refresh.setText("REFRESH");
        btn_refresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_refresh.setkBorderRadius(50);
        btn_refresh.setkEndColor(new java.awt.Color(204, 0, 204));
        btn_refresh.setkHoverEndColor(new java.awt.Color(204, 51, 255));
        btn_refresh.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_refresh.setkHoverStartColor(new java.awt.Color(51, 255, 255));
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/salary_female_100px.png"))); // NOI18N

        javax.swing.GroupLayout Color_form312Layout = new javax.swing.GroupLayout(Color_form312);
        Color_form312.setLayout(Color_form312Layout);
        Color_form312Layout.setHorizontalGroup(
            Color_form312Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Color_form312Layout.createSequentialGroup()
                .addGroup(Color_form312Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Color_form312Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Color_form312Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Color_form312Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Del, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Color_form312Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addGroup(Color_form312Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Color_form312Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_tk, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Color_form312Layout.createSequentialGroup()
                                        .addGap(676, 676, 676)
                                        .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(23, 23, 23))
        );
        Color_form312Layout.setVerticalGroup(
            Color_form312Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Color_form312Layout.createSequentialGroup()
                .addGroup(Color_form312Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Color_form312Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Color_form312Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(Color_form312Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField_tk, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(btn_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Del, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        formChinh_312.add(Color_form312, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(formChinh_312, javax.swing.GroupLayout.PREFERRED_SIZE, 974, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formChinh_312, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void btn_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditActionPerformed
       int otp = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa hay không?", "Confirm", JOptionPane.YES_OPTION);
        if(otp == JOptionPane.YES_OPTION){
            nhanVien_312 bk = new nhanVien_312();
            bk.setID(cbo_id.getSelectedItem().toString());
            bk.setName(txt_Name.getText());
            bk.setPosition(cbo_ChucVu.getSelectedItem().toString());
            bk.setEmail(txt_Email.getText());
            bk.setLuongcb(Double.parseDouble(txt_LuongCoBan.getText()));
            bk.setLuongthuong(Double.parseDouble(txt_LuongThuong.getText()));
            bk.setTinhtrang(daNhan312.isSelected());
            qlbd.updateUser(bk);
            showTable();
            JOptionPane.showMessageDialog(this, "Bạn đã sửa thông tin thành công!");
        }
    }//GEN-LAST:event_btn_EditActionPerformed

    private void btn_DelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DelActionPerformed
        selectedIndex = tb_Luong312.getSelectedRow();
        nhanVien_312 qltv = ql.get(selectedIndex);
        JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa không?");
        new luongNhanVienDao_119().delete(qltv.getID());
        showTable();
    }//GEN-LAST:event_btn_DelActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        String name = jTextField_tk.getText();
        if(name.length()>0){
            ql = new luongNhanVienDao_119().findTaiLieu(name);
            model.setRowCount(0);
            for(nhanVien_312 qly : ql){
            model.addRow(new Object[]{
                qly.getID(), qly.getName(), qly.getPosition(), qly.getEmail(), qly.getLuongcb(), qly.getLuongthuong(), qly.getLuongnhan(),qly.getTinhtrang()
                });
            }
        }else{
            jTextField_tk.setText("");
            showTable();
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        cbo_id.setSelectedItem(" ");
        txt_Name.setText("");
        cbo_ChucVu.setSelectedItem(".");
        txt_Email.setText("");
        txt_LuongCoBan.setText("");
        txt_LuongThuong.setText("");
        jTextField_tk.setText("");
        daNhan312.setSelected(false);
        daNhan312.setSelected(false);
//       showTable();  
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void cbo_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_idActionPerformed
        int index = cbo_id.getSelectedIndex();
        String value = cbo_id.getItemAt(index);
        nv = qlbd.find1TaiLieu(value);
        txt_Name.setText(nv.getName());
        cbo_ChucVu.setSelectedItem(nv.getPosition());
        txt_Email.setText(nv.getEmail());
        txt_LuongCoBan.setText(String.valueOf(nv.getLuongcb()));
        txt_LuongThuong.setText(String.valueOf(nv.getLuongthuong()));
        
    }//GEN-LAST:event_cbo_idActionPerformed

    private void jTextField_tkCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField_tkCaretUpdate
        // TODO add your handling code here:
        showTable();
    }//GEN-LAST:event_jTextField_tkCaretUpdate

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        for (double i = 0.0; i <=1.0; i = i+0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(50);
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void jTextField_tkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_tkActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField_tkActionPerformed

    private void jTextField_tkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_tkMouseClicked
        // TODO add your handling code here:
        jTextField_tk.setText("");
    }//GEN-LAST:event_jTextField_tkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DieuChinhLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DieuChinhLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DieuChinhLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DieuChinhLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DieuChinhLuong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KGradientPanel Color_form312;
    private com.k33ptoo.components.KButton btn_Del;
    private com.k33ptoo.components.KButton btn_Edit;
    private com.k33ptoo.components.KButton btn_Exit;
    private com.k33ptoo.components.KButton btn_refresh;
    private com.k33ptoo.components.KButton btn_search;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbo_ChucVu;
    private javax.swing.JComboBox<String> cbo_id;
    private javax.swing.JRadioButton chuaNhan312;
    private javax.swing.JRadioButton daNhan312;
    private javax.swing.JPanel formChinh_312;
    private javax.swing.JPanel formMin_312;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField_tk;
    private javax.swing.JTable tb_Luong312;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_LuongCoBan;
    private javax.swing.JTextField txt_LuongThuong;
    private javax.swing.JTextField txt_Name;
    // End of variables declaration//GEN-END:variables
    private void showTable() {
        ql =new luongNhanVienDao_119().getAllUsers();
        model.setRowCount(0);
        for(nhanVien_312 qly : ql){
            model.addRow(new Object[]{
                qly.getID(), qly.getName(), qly.getPosition(), qly.getEmail(), qly.getLuongcb(), qly.getLuongthuong(), qly.getLuongnhan(),qly.getTinhtrang()
            });
        }
    }
}
