/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.border.LineBorder;

/**
 *
 * @author ASUS
 */
public class Main extends javax.swing.JFrame {
    
     boolean a;   
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        Main.this.getRootPane().setBorder(new LineBorder(new Color(73,128,242)));
        
        //icontitle119.setText(this.getTitle());
        //title119.setText(this.getTitle());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        iocnMinMaxClose = new javax.swing.JPanel();
        btn_mini119 = new javax.swing.JLabel();
        btn_maximus119 = new javax.swing.JLabel();
        btn_close119 = new javax.swing.JLabel();
        title_header119 = new javax.swing.JPanel();
        icontitle119 = new javax.swing.JLabel();
        title119 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        MenuIcon = new javax.swing.JPanel();
        lineHidemenu = new javax.swing.JPanel();
        hideMenu = new javax.swing.JPanel();
        btn_Hidemenu = new javax.swing.JLabel();
        linehome = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        btn_Home = new javax.swing.JLabel();
        lineadd = new javax.swing.JPanel();
        add = new javax.swing.JPanel();
        btn_add = new javax.swing.JLabel();
        lineCalendar = new javax.swing.JPanel();
        Calender = new javax.swing.JPanel();
        btn_Calendar = new javax.swing.JLabel();
        lineEmail = new javax.swing.JPanel();
        Email = new javax.swing.JPanel();
        btn_Email = new javax.swing.JLabel();
        lineSetting = new javax.swing.JPanel();
        setting = new javax.swing.JPanel();
        btn_Setting = new javax.swing.JLabel();
        lineSearch = new javax.swing.JPanel();
        Search = new javax.swing.JPanel();
        btn_Search = new javax.swing.JLabel();
        lineEdit = new javax.swing.JPanel();
        Edit = new javax.swing.JPanel();
        btn_Edit = new javax.swing.JLabel();
        linerSalary = new javax.swing.JPanel();
        Salary = new javax.swing.JPanel();
        btn_Salary = new javax.swing.JLabel();
        lineRemove = new javax.swing.JPanel();
        Remove = new javax.swing.JPanel();
        btn_Remove = new javax.swing.JLabel();
        menuhide = new javax.swing.JPanel();
        jphome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jpadd = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        jpedit119 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jpfind = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jpcalculate = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpremove = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jplich = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jpgmail = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jpgmail1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        dashboardview = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Header.setBackground(new java.awt.Color(102, 102, 102));
        Header.setPreferredSize(new java.awt.Dimension(800, 30));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HeaderMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });
        Header.setLayout(new java.awt.BorderLayout());

        iocnMinMaxClose.setBackground(new java.awt.Color(102, 102, 102));
        iocnMinMaxClose.setPreferredSize(new java.awt.Dimension(80, 50));

        btn_mini119.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/subtract_18px.png"))); // NOI18N
        btn_mini119.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_mini119MousePressed(evt);
            }
        });
        iocnMinMaxClose.add(btn_mini119);

        btn_maximus119.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/rectangular_18px111.png"))); // NOI18N
        btn_maximus119.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_maximus119MousePressed(evt);
            }
        });
        iocnMinMaxClose.add(btn_maximus119);

        btn_close119.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/multiply_18px111.png"))); // NOI18N
        btn_close119.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_close119MousePressed(evt);
            }
        });
        iocnMinMaxClose.add(btn_close119);

        Header.add(iocnMinMaxClose, java.awt.BorderLayout.LINE_END);

        title_header119.setBackground(new java.awt.Color(102, 102, 102));
        title_header119.setPreferredSize(new java.awt.Dimension(150, 30));
        title_header119.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        icontitle119.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/staff_18px.png"))); // NOI18N
        title_header119.add(icontitle119);

        title119.setForeground(new java.awt.Color(255, 255, 255));
        title119.setText("Quản lý Nhân viên");
        title_header119.add(title119);

        Header.add(title_header119, java.awt.BorderLayout.LINE_START);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        menu.setPreferredSize(new java.awt.Dimension(250, 450));
        menu.setLayout(new java.awt.BorderLayout());

        MenuIcon.setBackground(new java.awt.Color(0, 145, 255));
        MenuIcon.setPreferredSize(new java.awt.Dimension(50, 450));
        MenuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lineHidemenu.setBackground(new java.awt.Color(0, 145, 255));
        lineHidemenu.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout lineHidemenuLayout = new javax.swing.GroupLayout(lineHidemenu);
        lineHidemenu.setLayout(lineHidemenuLayout);
        lineHidemenuLayout.setHorizontalGroup(
            lineHidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        lineHidemenuLayout.setVerticalGroup(
            lineHidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(lineHidemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 5));

        hideMenu.setBackground(new java.awt.Color(0, 145, 255));
        hideMenu.setPreferredSize(new java.awt.Dimension(50, 50));
        hideMenu.setLayout(new java.awt.BorderLayout());

        btn_Hidemenu.setBackground(new java.awt.Color(0, 255, 255));
        btn_Hidemenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Hidemenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back_to_20px.png"))); // NOI18N
        btn_Hidemenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_HidemenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_HidemenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_HidemenuMouseExited(evt);
            }
        });
        hideMenu.add(btn_Hidemenu, java.awt.BorderLayout.CENTER);

        MenuIcon.add(hideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 50, 50));

        linehome.setBackground(new java.awt.Color(0, 145, 255));
        linehome.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout linehomeLayout = new javax.swing.GroupLayout(linehome);
        linehome.setLayout(linehomeLayout);
        linehomeLayout.setHorizontalGroup(
            linehomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        linehomeLayout.setVerticalGroup(
            linehomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(linehome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 50, 5));

        home.setBackground(new java.awt.Color(0, 145, 255));
        home.setLayout(new java.awt.BorderLayout());

        btn_Home.setBackground(new java.awt.Color(0, 145, 255));
        btn_Home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home_20px.png"))); // NOI18N
        btn_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_HomeMouseExited(evt);
            }
        });
        home.add(btn_Home, java.awt.BorderLayout.CENTER);

        MenuIcon.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 50, 50));

        lineadd.setBackground(new java.awt.Color(0, 145, 255));
        lineadd.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout lineaddLayout = new javax.swing.GroupLayout(lineadd);
        lineadd.setLayout(lineaddLayout);
        lineaddLayout.setHorizontalGroup(
            lineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        lineaddLayout.setVerticalGroup(
            lineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(lineadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 50, -1));

        add.setBackground(new java.awt.Color(5, 10, 46));
        add.setLayout(new java.awt.BorderLayout());

        btn_add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add_20px.png"))); // NOI18N
        btn_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addMouseExited(evt);
            }
        });
        add.add(btn_add, java.awt.BorderLayout.CENTER);

        MenuIcon.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 115, 50, 50));

        lineCalendar.setBackground(new java.awt.Color(5, 10, 46));
        lineCalendar.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout lineCalendarLayout = new javax.swing.GroupLayout(lineCalendar);
        lineCalendar.setLayout(lineCalendarLayout);
        lineCalendarLayout.setHorizontalGroup(
            lineCalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        lineCalendarLayout.setVerticalGroup(
            lineCalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(lineCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 50, -1));

        Calender.setBackground(new java.awt.Color(5, 10, 46));
        Calender.setPreferredSize(new java.awt.Dimension(50, 50));
        Calender.setLayout(new java.awt.BorderLayout());

        btn_Calendar.setBackground(new java.awt.Color(0, 255, 255));
        btn_Calendar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Calendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Tear-Off Calendar_20px.png"))); // NOI18N
        btn_Calendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CalendarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CalendarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CalendarMouseExited(evt);
            }
        });
        Calender.add(btn_Calendar, java.awt.BorderLayout.CENTER);

        MenuIcon.add(Calender, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 515, 50, -1));

        lineEmail.setBackground(new java.awt.Color(5, 10, 46));
        lineEmail.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout lineEmailLayout = new javax.swing.GroupLayout(lineEmail);
        lineEmail.setLayout(lineEmailLayout);
        lineEmailLayout.setHorizontalGroup(
            lineEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        lineEmailLayout.setVerticalGroup(
            lineEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(lineEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 565, 50, 5));

        Email.setBackground(new java.awt.Color(5, 10, 46));
        Email.setPreferredSize(new java.awt.Dimension(50, 50));
        Email.setLayout(new java.awt.BorderLayout());

        btn_Email.setBackground(new java.awt.Color(0, 255, 255));
        btn_Email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/mail_20px.png"))); // NOI18N
        btn_Email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EmailMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_EmailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EmailMouseExited(evt);
            }
        });
        Email.add(btn_Email, java.awt.BorderLayout.CENTER);

        MenuIcon.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 50, 50));

        lineSetting.setBackground(new java.awt.Color(5, 10, 46));
        lineSetting.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout lineSettingLayout = new javax.swing.GroupLayout(lineSetting);
        lineSetting.setLayout(lineSettingLayout);
        lineSettingLayout.setHorizontalGroup(
            lineSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        lineSettingLayout.setVerticalGroup(
            lineSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(lineSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 50, 5));

        setting.setBackground(new java.awt.Color(5, 10, 46));
        setting.setPreferredSize(new java.awt.Dimension(50, 50));
        setting.setLayout(new java.awt.BorderLayout());

        btn_Setting.setBackground(new java.awt.Color(0, 255, 255));
        btn_Setting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/settings_20px.png"))); // NOI18N
        btn_Setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SettingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_SettingMouseExited(evt);
            }
        });
        setting.add(btn_Setting, java.awt.BorderLayout.CENTER);

        MenuIcon.add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 625, 50, 50));

        lineSearch.setBackground(new java.awt.Color(5, 10, 46));
        lineSearch.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout lineSearchLayout = new javax.swing.GroupLayout(lineSearch);
        lineSearch.setLayout(lineSearchLayout);
        lineSearchLayout.setHorizontalGroup(
            lineSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        lineSearchLayout.setVerticalGroup(
            lineSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(lineSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 165, 50, -1));

        Search.setBackground(new java.awt.Color(5, 10, 46));
        Search.setLayout(new java.awt.BorderLayout());

        btn_Search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search_20px.png"))); // NOI18N
        btn_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_SearchMouseExited(evt);
            }
        });
        Search.add(btn_Search, java.awt.BorderLayout.CENTER);

        MenuIcon.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 50, 50));

        lineEdit.setBackground(new java.awt.Color(5, 10, 46));
        lineEdit.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout lineEditLayout = new javax.swing.GroupLayout(lineEdit);
        lineEdit.setLayout(lineEditLayout);
        lineEditLayout.setHorizontalGroup(
            lineEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        lineEditLayout.setVerticalGroup(
            lineEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(lineEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 50, 5));

        Edit.setBackground(new java.awt.Color(5, 10, 46));
        Edit.setLayout(new java.awt.BorderLayout());

        btn_Edit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit_20px.png"))); // NOI18N
        btn_Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_EditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EditMouseExited(evt);
            }
        });
        Edit.add(btn_Edit, java.awt.BorderLayout.CENTER);

        MenuIcon.add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 225, 50, 50));

        linerSalary.setBackground(new java.awt.Color(5, 10, 46));
        linerSalary.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout linerSalaryLayout = new javax.swing.GroupLayout(linerSalary);
        linerSalary.setLayout(linerSalaryLayout);
        linerSalaryLayout.setHorizontalGroup(
            linerSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        linerSalaryLayout.setVerticalGroup(
            linerSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(linerSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 275, 50, -1));

        Salary.setBackground(new java.awt.Color(5, 10, 46));
        Salary.setLayout(new java.awt.BorderLayout());

        btn_Salary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Salary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/calculate_20px.png"))); // NOI18N
        btn_Salary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SalaryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SalaryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_SalaryMouseExited(evt);
            }
        });
        Salary.add(btn_Salary, java.awt.BorderLayout.CENTER);

        MenuIcon.add(Salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 50, 50));

        lineRemove.setBackground(new java.awt.Color(5, 10, 46));
        lineRemove.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout lineRemoveLayout = new javax.swing.GroupLayout(lineRemove);
        lineRemove.setLayout(lineRemoveLayout);
        lineRemoveLayout.setHorizontalGroup(
            lineRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        lineRemoveLayout.setVerticalGroup(
            lineRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(lineRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 50, -1));

        Remove.setBackground(new java.awt.Color(5, 10, 46));
        Remove.setLayout(new java.awt.BorderLayout());

        btn_Remove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/trash_20px.png"))); // NOI18N
        btn_Remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_RemoveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_RemoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_RemoveMouseExited(evt);
            }
        });
        Remove.add(btn_Remove, java.awt.BorderLayout.CENTER);

        MenuIcon.add(Remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 335, 50, 50));

        menu.add(MenuIcon, java.awt.BorderLayout.LINE_START);

        menuhide.setBackground(new java.awt.Color(25, 29, 74));
        menuhide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jphome.setBackground(new java.awt.Color(25, 29, 74));
        jphome.setPreferredSize(new java.awt.Dimension(220, 55));
        jphome.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Home");
        jphome.add(jLabel2, java.awt.BorderLayout.CENTER);

        menuhide.add(jphome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 200, 55));

        jpadd.setBackground(new java.awt.Color(25, 29, 74));
        jpadd.setPreferredSize(new java.awt.Dimension(220, 55));
        jpadd.setLayout(new java.awt.BorderLayout());

        kGradientPanel2.setkEndColor(new java.awt.Color(0, 0, 153));
        kGradientPanel2.setkGradientFocus(300);
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 145, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add Employees");

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 45, Short.MAX_VALUE)))
        );

        jpadd.add(kGradientPanel2, java.awt.BorderLayout.PAGE_START);

        menuhide.add(jpadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 200, 55));

        jpedit119.setBackground(new java.awt.Color(25, 29, 74));
        jpedit119.setPreferredSize(new java.awt.Dimension(220, 55));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Edit");

        javax.swing.GroupLayout jpedit119Layout = new javax.swing.GroupLayout(jpedit119);
        jpedit119.setLayout(jpedit119Layout);
        jpedit119Layout.setHorizontalGroup(
            jpedit119Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpedit119Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpedit119Layout.setVerticalGroup(
            jpedit119Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpedit119Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menuhide.add(jpedit119, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 200, 55));

        jpfind.setBackground(new java.awt.Color(25, 29, 74));
        jpfind.setPreferredSize(new java.awt.Dimension(220, 55));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Search");

        javax.swing.GroupLayout jpfindLayout = new javax.swing.GroupLayout(jpfind);
        jpfind.setLayout(jpfindLayout);
        jpfindLayout.setHorizontalGroup(
            jpfindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpfindLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpfindLayout.setVerticalGroup(
            jpfindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpfindLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuhide.add(jpfind, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 165, 200, 55));

        jpcalculate.setBackground(new java.awt.Color(25, 29, 74));
        jpcalculate.setPreferredSize(new java.awt.Dimension(220, 55));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Salary");

        javax.swing.GroupLayout jpcalculateLayout = new javax.swing.GroupLayout(jpcalculate);
        jpcalculate.setLayout(jpcalculateLayout);
        jpcalculateLayout.setHorizontalGroup(
            jpcalculateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpcalculateLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpcalculateLayout.setVerticalGroup(
            jpcalculateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpcalculateLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuhide.add(jpcalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 275, 200, 55));

        jpremove.setBackground(new java.awt.Color(25, 29, 74));
        jpremove.setPreferredSize(new java.awt.Dimension(220, 55));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Remove");

        javax.swing.GroupLayout jpremoveLayout = new javax.swing.GroupLayout(jpremove);
        jpremove.setLayout(jpremoveLayout);
        jpremoveLayout.setHorizontalGroup(
            jpremoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpremoveLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpremoveLayout.setVerticalGroup(
            jpremoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpremoveLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menuhide.add(jpremove, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 200, 55));

        jplich.setBackground(new java.awt.Color(25, 29, 74));
        jplich.setPreferredSize(new java.awt.Dimension(220, 55));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Calendar");

        javax.swing.GroupLayout jplichLayout = new javax.swing.GroupLayout(jplich);
        jplich.setLayout(jplichLayout);
        jplichLayout.setHorizontalGroup(
            jplichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplichLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jplichLayout.setVerticalGroup(
            jplichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplichLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menuhide.add(jplich, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 200, 55));

        jpgmail.setBackground(new java.awt.Color(25, 29, 74));
        jpgmail.setPreferredSize(new java.awt.Dimension(220, 55));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Email");

        javax.swing.GroupLayout jpgmailLayout = new javax.swing.GroupLayout(jpgmail);
        jpgmail.setLayout(jpgmailLayout);
        jpgmailLayout.setHorizontalGroup(
            jpgmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpgmailLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpgmailLayout.setVerticalGroup(
            jpgmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpgmailLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menuhide.add(jpgmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 565, 200, 55));

        jpgmail1.setBackground(new java.awt.Color(25, 29, 74));
        jpgmail1.setPreferredSize(new java.awt.Dimension(220, 55));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Setting");

        javax.swing.GroupLayout jpgmail1Layout = new javax.swing.GroupLayout(jpgmail1);
        jpgmail1.setLayout(jpgmail1Layout);
        jpgmail1Layout.setHorizontalGroup(
            jpgmail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpgmail1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpgmail1Layout.setVerticalGroup(
            jpgmail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpgmail1Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menuhide.add(jpgmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 200, 55));

        kGradientPanel1.setkEndColor(new java.awt.Color(102, 255, 204));
        kGradientPanel1.setkGradientFocus(200);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        menuhide.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 700));

        menu.add(menuhide, java.awt.BorderLayout.CENTER);

        getContentPane().add(menu, java.awt.BorderLayout.LINE_START);

        dashboardview.setBackground(new java.awt.Color(255, 204, 102));

        javax.swing.GroupLayout dashboardviewLayout = new javax.swing.GroupLayout(dashboardview);
        dashboardview.setLayout(dashboardviewLayout);
        dashboardviewLayout.setHorizontalGroup(
            dashboardviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
        );
        dashboardviewLayout.setVerticalGroup(
            dashboardviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        getContentPane().add(dashboardview, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1031, 730));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int xx_119, xy_119;
    public void changecolor (JPanel hover , Color rand){
        hover.setBackground(rand);        
    }
     public void clickmenu(JPanel h1, JPanel h2, int numberbool){
        if(numberbool == 1){
            h1.setBackground(new Color(25, 29, 74));
            h2.setBackground(new Color(0,145,255));
        }
        else{
            h1.setBackground(new Color(0,145,255));
            h2.setBackground(new Color(25, 29, 74));
        }
    }
          public void changeimage(JLabel button, String resourcheimg){
        ImageIcon aimg = new ImageIcon(getClass().getResource(resourcheimg));
        button.setIcon(aimg);
    }
    public void hideshow(JPanel menushowhide, boolean dashboard, JLabel button){
        if(dashboard == true){
            menushowhide.setPreferredSize(new Dimension(50, menushowhide.getHeight()));
            changeimage(button, "/icon/Hamburger Menu_20px.png");
        }
        else{
            menushowhide.setPreferredSize(new Dimension(250, menushowhide.getHeight()));
            changeimage(button, "/icon/back_to_20px.png");
        }
        
    }
        
    private void btn_HidemenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HidemenuMouseClicked
        clickmenu(hideMenu, kGradientPanel2, 1);
        // create  void  for  methode hide and show panel menu
        //(tạo khoảng trống cho menu bảng điều khiển ẩn và hiện methode)
        if(a==true){
          hideshow(menu, a, btn_Hidemenu);
          SwingUtilities.updateComponentTreeUI(this);
          //create methode change image
          
          a=false;
        }
        else{
            hideshow(menu, a, btn_Hidemenu);
            SwingUtilities.updateComponentTreeUI(this);
            a=true;
        }
    }//GEN-LAST:event_btn_HidemenuMouseClicked

    private void btn_HidemenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HidemenuMouseEntered
        changecolor(lineHidemenu, new Color(247,78,105));
    }//GEN-LAST:event_btn_HidemenuMouseEntered

    private void btn_HidemenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HidemenuMouseExited
       changecolor(lineHidemenu, new Color(5,10,46));
    }//GEN-LAST:event_btn_HidemenuMouseExited

    private void btn_maximus119MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_maximus119MousePressed
        // TODO add your handling code here:
        setColor(btn_maximus119);
        if(Main.this.getExtendedState() == MAXIMIZED_BOTH){
                Main.this.setExtendedState(JFrame.NORMAL);
            }
            else{
                Main.this.setExtendedState(MAXIMIZED_BOTH);
            }  
    }//GEN-LAST:event_btn_maximus119MousePressed

    private void btn_close119MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_close119MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_close119MousePressed

    private void btn_mini119MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mini119MousePressed
        // TODO add your handling code here:
        Main.this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btn_mini119MousePressed

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        // TODO add your handling code here:
        xx_119 = evt.getX();
        xy_119 = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx_119, y-xy_119);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2 && !evt.isConsumed()){
            if(Main.this.getExtendedState() == MAXIMIZED_BOTH){
                Main.this.setExtendedState(JFrame.NORMAL);
            }
            else{
                Main.this.setExtendedState(WIDTH);
            }
        }
    }//GEN-LAST:event_HeaderMouseClicked

    private void btn_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseClicked
        // TODO add your handling code here:
        clickmenu(add,kGradientPanel2, 1);    
    }//GEN-LAST:event_btn_addMouseClicked

    private void btn_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseEntered
        // TODO add your handling code here:
        changecolor(lineadd, new Color(247,78,105));
    }//GEN-LAST:event_btn_addMouseEntered

    private void btn_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseExited
        // TODO add your handling code here:
        changecolor(lineadd, new Color(0,145,255));
    }//GEN-LAST:event_btn_addMouseExited

    private void btn_SettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SettingMouseClicked
        // TODO add your handling code here:
        clickmenu(setting,Email, 1);
    }//GEN-LAST:event_btn_SettingMouseClicked

    private void btn_SettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SettingMouseEntered
        // TODO add your handling code here:
         changecolor(lineSetting, new Color(247,78,105));
    }//GEN-LAST:event_btn_SettingMouseEntered

    private void btn_SettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SettingMouseExited
        // TODO add your handling code here:
        changecolor(lineSetting, new Color(0,145,255));
    }//GEN-LAST:event_btn_SettingMouseExited

    private void btn_EmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmailMouseClicked
        // TODO add your handling code here:
        clickmenu(Email,Calender, 1);
    }//GEN-LAST:event_btn_EmailMouseClicked

    private void btn_EmailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmailMouseEntered
        // TODO add your handling code here:
         changecolor(lineEmail, new Color(247,78,105));
    }//GEN-LAST:event_btn_EmailMouseEntered

    private void btn_EmailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmailMouseExited
        // TODO add your handling code here:
        changecolor(lineEmail, new Color(0,145,255));
    }//GEN-LAST:event_btn_EmailMouseExited

    private void btn_CalendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CalendarMouseClicked
        // TODO add your handling code here:
        clickmenu(Calender,Remove, 1);
    }//GEN-LAST:event_btn_CalendarMouseClicked

    private void btn_CalendarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CalendarMouseEntered
        // TODO add your handling code here:
         changecolor(lineCalendar, new Color(247,78,105));
    }//GEN-LAST:event_btn_CalendarMouseEntered

    private void btn_CalendarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CalendarMouseExited
        // TODO add your handling code here:
        changecolor(lineCalendar, new Color(0,145,255));
    }//GEN-LAST:event_btn_CalendarMouseExited

    private void btn_SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SearchMouseClicked
        // TODO add your handling code here:
        clickmenu(Search,add, 1);
    }//GEN-LAST:event_btn_SearchMouseClicked

    private void btn_SearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SearchMouseEntered
        // TODO add your handling code here:
        changecolor(lineSearch, new Color(247,78,105));
    }//GEN-LAST:event_btn_SearchMouseEntered

    private void btn_SearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SearchMouseExited
        // TODO add your handling code here:
        changecolor(lineSearch, new Color(0,145,255));
    }//GEN-LAST:event_btn_SearchMouseExited

    private void btn_EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditMouseClicked
        // TODO add your handling code here:
        clickmenu(Edit,Search, 1);
    }//GEN-LAST:event_btn_EditMouseClicked

    private void btn_EditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditMouseEntered
        // TODO add your handling code here:
        changecolor(lineEdit, new Color(247,78,105));
    }//GEN-LAST:event_btn_EditMouseEntered

    private void btn_EditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditMouseExited
        // TODO add your handling code here:
        changecolor(lineEdit, new Color(0,145,255));
    }//GEN-LAST:event_btn_EditMouseExited

    private void btn_SalaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SalaryMouseClicked
        // TODO add your handling code here:
        clickmenu(Salary,Edit, 1);
    }//GEN-LAST:event_btn_SalaryMouseClicked

    private void btn_SalaryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SalaryMouseEntered
        // TODO add your handling code here:
        changecolor(linerSalary, new Color(247,78,105));
    }//GEN-LAST:event_btn_SalaryMouseEntered

    private void btn_SalaryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SalaryMouseExited
        // TODO add your handling code here:
        changecolor(linerSalary, new Color(0,145,255));
    }//GEN-LAST:event_btn_SalaryMouseExited

    private void btn_RemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RemoveMouseClicked
        // TODO add your handling code here:
        clickmenu(Remove,Salary, 1);
    }//GEN-LAST:event_btn_RemoveMouseClicked

    private void btn_RemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RemoveMouseEntered
        // TODO add your handling code here:
        changecolor(lineRemove, new Color(247,78,105));
    }//GEN-LAST:event_btn_RemoveMouseEntered

    private void btn_RemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RemoveMouseExited
        // TODO add your handling code here:
        changecolor(lineRemove, new Color(0,145,255));
    }//GEN-LAST:event_btn_RemoveMouseExited

    private void btn_HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseExited
        changecolor(linehome, new Color(0,145,255));
    }//GEN-LAST:event_btn_HomeMouseExited

    private void btn_HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseEntered
        changecolor(linehome, new Color(247,78,105));
    }//GEN-LAST:event_btn_HomeMouseEntered

    private void btn_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseClicked
        clickmenu(home,hideMenu, 1);
    }//GEN-LAST:event_btn_HomeMouseClicked

    private void setColor(JLabel pane){
        pane.setBackground(new Color(204,0,0));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    private void setColor(JPanel pane){
        pane.setBackground(new Color(41,57,80));
    }
    private void setColor1(JPanel pane){
        pane.setBackground(new Color(41,57,80));
    }
    private void resetColor(JPanel [] pane, JPanel [] indicator){
        for(int i=0; i<pane.length; i++){
            pane[i].setBackground(new Color(23,35,51));
        }
        for(int i=0; i<indicator.length; i++){
            indicator[i].setOpaque(false);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Calender;
    private javax.swing.JPanel Edit;
    private javax.swing.JPanel Email;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel MenuIcon;
    private javax.swing.JPanel Remove;
    private javax.swing.JPanel Salary;
    private javax.swing.JPanel Search;
    private javax.swing.JPanel add;
    private javax.swing.JLabel btn_Calendar;
    private javax.swing.JLabel btn_Edit;
    private javax.swing.JLabel btn_Email;
    private javax.swing.JLabel btn_Hidemenu;
    private javax.swing.JLabel btn_Home;
    private javax.swing.JLabel btn_Remove;
    private javax.swing.JLabel btn_Salary;
    private javax.swing.JLabel btn_Search;
    private javax.swing.JLabel btn_Setting;
    private javax.swing.JLabel btn_add;
    private javax.swing.JLabel btn_close119;
    private javax.swing.JLabel btn_maximus119;
    private javax.swing.JLabel btn_mini119;
    private javax.swing.JPanel dashboardview;
    private javax.swing.JPanel hideMenu;
    private javax.swing.JPanel home;
    private javax.swing.JLabel icontitle119;
    private javax.swing.JPanel iocnMinMaxClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jpadd;
    private javax.swing.JPanel jpcalculate;
    private javax.swing.JPanel jpedit119;
    private javax.swing.JPanel jpfind;
    private javax.swing.JPanel jpgmail;
    private javax.swing.JPanel jpgmail1;
    private javax.swing.JPanel jphome;
    private javax.swing.JPanel jplich;
    private javax.swing.JPanel jpremove;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JPanel lineCalendar;
    private javax.swing.JPanel lineEdit;
    private javax.swing.JPanel lineEmail;
    private javax.swing.JPanel lineHidemenu;
    private javax.swing.JPanel lineRemove;
    private javax.swing.JPanel lineSearch;
    private javax.swing.JPanel lineSetting;
    private javax.swing.JPanel lineadd;
    private javax.swing.JPanel linehome;
    private javax.swing.JPanel linerSalary;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuhide;
    private javax.swing.JPanel setting;
    private javax.swing.JLabel title119;
    private javax.swing.JPanel title_header119;
    // End of variables declaration//GEN-END:variables
}
