/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import Connect.NhanVienDAO;
import Service.Service;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import model.nhanVien;

/**
 *
 * @author ASUS
 */
public class Main extends javax.swing.JFrame {
    int selectedIndex;
    Service qlService;
    DefaultTableModel defaultTableModel;
    private List<nhanVien> ql;
    private DefaultTableModel model;
     boolean a; 
     JPanel [] panels;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        Main.this.getRootPane().setBorder(new LineBorder(new Color(73,128,242)));
        showTime();
        showDate();
        qlthongtin.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        qlthongtin.getTableHeader().setOpaque(false);
        qlthongtin.getTableHeader().setBackground(new Color(0, 139, 139));
        qlthongtin.getTableHeader().setForeground(new Color(255,255,240));
        qlthongtin.setRowHeight(25);
        model = (DefaultTableModel)qlthongtin.getModel();
        showTable();
        //icontitle119.setText(this.getTitle());
        //title119.setText(this.getTitle());
    }
    private void setTableData(List<nhanVien> ql){
        for (nhanVien qly : ql){
            defaultTableModel.addRow(new Object[]{qly.getID(), qly.getName(), qly.getSex(), qly.getAddress(), qly.getPhone(), qly.getEmail(), qly.getDateOfBirth(), qly.getPosition()});
            
        }
    }
    void showTime(){
         new Timer(0, new ActionListener(){
             @Override
             public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                Time.setText(s.format(d));
             }
             
             
         }).start();
    }
    void showDate(){
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        date.setText(s.format(d));
        
    }
    public void addLabelToTable(){
        panels = new JPanel[]{hideMenu, home, add, Calender, Email, setting, Search, Edit, Salary, Remove};
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        iocnMinMaxClose = new javax.swing.JPanel();
        btn_mini119 = new javax.swing.JLabel();
        btn_maximus119 = new javax.swing.JLabel();
        btn_close119 = new javax.swing.JLabel();
        title_header119 = new javax.swing.JPanel();
        icontitle119 = new javax.swing.JLabel();
        title119 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        MenuIcon = new javax.swing.JPanel();
        lineHidemenu = new javax.swing.JPanel();
        hideMenu = new javax.swing.JPanel();
        btn_Hidemenu = new javax.swing.JLabel();
        linehome = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        btn_Home = new javax.swing.JLabel();
        lineadd = new javax.swing.JPanel();
        add = new javax.swing.JPanel();
        btn_add = new javax.swing.JLabel();
        lineCalendar = new javax.swing.JPanel();
        Calender = new javax.swing.JPanel();
        btn_Calendar = new javax.swing.JLabel();
        lineEmail = new javax.swing.JPanel();
        Email = new javax.swing.JPanel();
        btn_Email = new javax.swing.JLabel();
        lineSetting = new javax.swing.JPanel();
        setting = new javax.swing.JPanel();
        btn_Setting = new javax.swing.JLabel();
        lineSearch = new javax.swing.JPanel();
        Search = new javax.swing.JPanel();
        btn_Search = new javax.swing.JLabel();
        lineEdit = new javax.swing.JPanel();
        Edit = new javax.swing.JPanel();
        btn_Edit = new javax.swing.JLabel();
        linerSalary = new javax.swing.JPanel();
        Salary = new javax.swing.JPanel();
        btn_Salary = new javax.swing.JLabel();
        lineRemove = new javax.swing.JPanel();
        Remove = new javax.swing.JPanel();
        btn_Remove = new javax.swing.JLabel();
        menuhide = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        txt_home = new javax.swing.JLabel();
        txt_add = new javax.swing.JLabel();
        txt_search = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        dashboardview = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        kGradientPanel9 = new keeptoo.KGradientPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        kGradientPanel10 = new keeptoo.KGradientPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        kGradientPanel15 = new keeptoo.KGradientPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        qlthongtin = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Header.setBackground(new java.awt.Color(102, 102, 102));
        Header.setPreferredSize(new java.awt.Dimension(800, 30));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HeaderMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });
        Header.setLayout(new java.awt.BorderLayout());

        iocnMinMaxClose.setBackground(new java.awt.Color(102, 102, 102));
        iocnMinMaxClose.setPreferredSize(new java.awt.Dimension(80, 50));

        btn_mini119.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/subtract_18px.png"))); // NOI18N
        btn_mini119.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_mini119MousePressed(evt);
            }
        });
        iocnMinMaxClose.add(btn_mini119);

        btn_maximus119.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/rectangular_18px111.png"))); // NOI18N
        btn_maximus119.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_maximus119MousePressed(evt);
            }
        });
        iocnMinMaxClose.add(btn_maximus119);

        btn_close119.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/multiply_18px111.png"))); // NOI18N
        btn_close119.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_close119MousePressed(evt);
            }
        });
        iocnMinMaxClose.add(btn_close119);

        Header.add(iocnMinMaxClose, java.awt.BorderLayout.LINE_END);

        title_header119.setBackground(new java.awt.Color(102, 102, 102));
        title_header119.setPreferredSize(new java.awt.Dimension(150, 30));
        title_header119.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        icontitle119.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/staff_18px.png"))); // NOI18N
        title_header119.add(icontitle119);

        title119.setForeground(new java.awt.Color(255, 255, 255));
        title119.setText("Quản lý Nhân viên");
        title_header119.add(title119);

        Header.add(title_header119, java.awt.BorderLayout.LINE_START);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        menu.setPreferredSize(new java.awt.Dimension(250, 450));
        menu.setLayout(new java.awt.BorderLayout());

        MenuIcon.setBackground(new java.awt.Color(0, 145, 255));
        MenuIcon.setPreferredSize(new java.awt.Dimension(50, 450));
        MenuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lineHidemenu.setBackground(new java.awt.Color(0, 145, 255));
        lineHidemenu.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout lineHidemenuLayout = new javax.swing.GroupLayout(lineHidemenu);
        lineHidemenu.setLayout(lineHidemenuLayout);
        lineHidemenuLayout.setHorizontalGroup(
            lineHidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        lineHidemenuLayout.setVerticalGroup(
            lineHidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(lineHidemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 5));

        hideMenu.setBackground(new java.awt.Color(0, 145, 255));
        hideMenu.setPreferredSize(new java.awt.Dimension(50, 50));
        hideMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                hideMenuMouseMoved(evt);
            }
        });
        hideMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hideMenuMouseExited(evt);
            }
        });
        hideMenu.setLayout(new java.awt.BorderLayout());

        btn_Hidemenu.setBackground(new java.awt.Color(0, 255, 255));
        btn_Hidemenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Hidemenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back_to_20px.png"))); // NOI18N
        btn_Hidemenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_HidemenuMouseMoved(evt);
            }
        });
        btn_Hidemenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_HidemenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_HidemenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_HidemenuMouseExited(evt);
            }
        });
        hideMenu.add(btn_Hidemenu, java.awt.BorderLayout.CENTER);

        MenuIcon.add(hideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 50, 50));

        linehome.setBackground(new java.awt.Color(0, 145, 255));
        linehome.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout linehomeLayout = new javax.swing.GroupLayout(linehome);
        linehome.setLayout(linehomeLayout);
        linehomeLayout.setHorizontalGroup(
            linehomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        linehomeLayout.setVerticalGroup(
            linehomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(linehome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 50, 5));

        home.setBackground(new java.awt.Color(0, 145, 255));
        home.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                homeMouseMoved(evt);
            }
        });
        home.setLayout(new java.awt.BorderLayout());

        btn_Home.setBackground(new java.awt.Color(0, 145, 255));
        btn_Home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home_20px.png"))); // NOI18N
        btn_Home.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_HomeMouseMoved(evt);
            }
        });
        btn_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_HomeMouseExited(evt);
            }
        });
        home.add(btn_Home, java.awt.BorderLayout.CENTER);

        MenuIcon.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 50, 50));

        lineadd.setBackground(new java.awt.Color(0, 145, 255));
        lineadd.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout lineaddLayout = new javax.swing.GroupLayout(lineadd);
        lineadd.setLayout(lineaddLayout);
        lineaddLayout.setHorizontalGroup(
            lineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        lineaddLayout.setVerticalGroup(
            lineaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(lineadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 50, -1));

        add.setBackground(new java.awt.Color(0, 145, 255));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.setLayout(new java.awt.BorderLayout());

        btn_add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add_20px.png"))); // NOI18N
        btn_add.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_addMouseMoved(evt);
            }
        });
        btn_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addMouseExited(evt);
            }
        });
        add.add(btn_add, java.awt.BorderLayout.CENTER);

        MenuIcon.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 115, 50, 50));

        lineCalendar.setBackground(new java.awt.Color(0, 145, 255));
        lineCalendar.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout lineCalendarLayout = new javax.swing.GroupLayout(lineCalendar);
        lineCalendar.setLayout(lineCalendarLayout);
        lineCalendarLayout.setHorizontalGroup(
            lineCalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        lineCalendarLayout.setVerticalGroup(
            lineCalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(lineCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 50, -1));

        Calender.setBackground(new java.awt.Color(0, 145, 255));
        Calender.setPreferredSize(new java.awt.Dimension(50, 50));
        Calender.setLayout(new java.awt.BorderLayout());

        btn_Calendar.setBackground(new java.awt.Color(0, 255, 255));
        btn_Calendar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Calendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Tear-Off Calendar_20px.png"))); // NOI18N
        btn_Calendar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_CalendarMouseMoved(evt);
            }
        });
        btn_Calendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CalendarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CalendarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CalendarMouseExited(evt);
            }
        });
        Calender.add(btn_Calendar, java.awt.BorderLayout.CENTER);

        MenuIcon.add(Calender, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 515, 50, -1));

        lineEmail.setBackground(new java.awt.Color(0, 145, 255));
        lineEmail.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout lineEmailLayout = new javax.swing.GroupLayout(lineEmail);
        lineEmail.setLayout(lineEmailLayout);
        lineEmailLayout.setHorizontalGroup(
            lineEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        lineEmailLayout.setVerticalGroup(
            lineEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(lineEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 565, 50, 5));

        Email.setBackground(new java.awt.Color(0, 145, 255));
        Email.setPreferredSize(new java.awt.Dimension(50, 50));
        Email.setLayout(new java.awt.BorderLayout());

        btn_Email.setBackground(new java.awt.Color(0, 255, 255));
        btn_Email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/mail_20px.png"))); // NOI18N
        btn_Email.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_EmailMouseMoved(evt);
            }
        });
        btn_Email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EmailMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_EmailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EmailMouseExited(evt);
            }
        });
        Email.add(btn_Email, java.awt.BorderLayout.CENTER);

        MenuIcon.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 50, 50));

        lineSetting.setBackground(new java.awt.Color(0, 145, 255));
        lineSetting.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout lineSettingLayout = new javax.swing.GroupLayout(lineSetting);
        lineSetting.setLayout(lineSettingLayout);
        lineSettingLayout.setHorizontalGroup(
            lineSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        lineSettingLayout.setVerticalGroup(
            lineSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(lineSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 50, 5));

        setting.setBackground(new java.awt.Color(0, 145, 255));
        setting.setPreferredSize(new java.awt.Dimension(50, 50));
        setting.setLayout(new java.awt.BorderLayout());

        btn_Setting.setBackground(new java.awt.Color(0, 255, 255));
        btn_Setting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/settings_20px.png"))); // NOI18N
        btn_Setting.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_SettingMouseMoved(evt);
            }
        });
        btn_Setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SettingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_SettingMouseExited(evt);
            }
        });
        setting.add(btn_Setting, java.awt.BorderLayout.CENTER);

        MenuIcon.add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 625, 50, 50));

        lineSearch.setBackground(new java.awt.Color(0, 145, 255));
        lineSearch.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout lineSearchLayout = new javax.swing.GroupLayout(lineSearch);
        lineSearch.setLayout(lineSearchLayout);
        lineSearchLayout.setHorizontalGroup(
            lineSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        lineSearchLayout.setVerticalGroup(
            lineSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(lineSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 165, 50, -1));

        Search.setBackground(new java.awt.Color(0, 145, 255));
        Search.setLayout(new java.awt.BorderLayout());

        btn_Search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search_20px.png"))); // NOI18N
        btn_Search.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_SearchMouseMoved(evt);
            }
        });
        btn_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_SearchMouseExited(evt);
            }
        });
        Search.add(btn_Search, java.awt.BorderLayout.CENTER);

        MenuIcon.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 50, 50));

        lineEdit.setBackground(new java.awt.Color(0, 145, 255));
        lineEdit.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout lineEditLayout = new javax.swing.GroupLayout(lineEdit);
        lineEdit.setLayout(lineEditLayout);
        lineEditLayout.setHorizontalGroup(
            lineEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        lineEditLayout.setVerticalGroup(
            lineEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(lineEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 50, 5));

        Edit.setBackground(new java.awt.Color(0, 145, 255));
        Edit.setLayout(new java.awt.BorderLayout());

        btn_Edit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit_20px.png"))); // NOI18N
        btn_Edit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_EditMouseMoved(evt);
            }
        });
        btn_Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_EditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EditMouseExited(evt);
            }
        });
        Edit.add(btn_Edit, java.awt.BorderLayout.CENTER);

        MenuIcon.add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 225, 50, 50));

        linerSalary.setBackground(new java.awt.Color(0, 145, 255));
        linerSalary.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout linerSalaryLayout = new javax.swing.GroupLayout(linerSalary);
        linerSalary.setLayout(linerSalaryLayout);
        linerSalaryLayout.setHorizontalGroup(
            linerSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        linerSalaryLayout.setVerticalGroup(
            linerSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(linerSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 275, 50, -1));

        Salary.setBackground(new java.awt.Color(0, 145, 255));
        Salary.setLayout(new java.awt.BorderLayout());

        btn_Salary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Salary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/calculate_20px.png"))); // NOI18N
        btn_Salary.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_SalaryMouseMoved(evt);
            }
        });
        btn_Salary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SalaryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SalaryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_SalaryMouseExited(evt);
            }
        });
        Salary.add(btn_Salary, java.awt.BorderLayout.CENTER);

        MenuIcon.add(Salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 50, 50));

        lineRemove.setBackground(new java.awt.Color(0, 145, 255));
        lineRemove.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout lineRemoveLayout = new javax.swing.GroupLayout(lineRemove);
        lineRemove.setLayout(lineRemoveLayout);
        lineRemoveLayout.setHorizontalGroup(
            lineRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        lineRemoveLayout.setVerticalGroup(
            lineRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(lineRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 50, -1));

        Remove.setBackground(new java.awt.Color(0, 145, 255));
        Remove.setLayout(new java.awt.BorderLayout());

        btn_Remove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/trash_20px.png"))); // NOI18N
        btn_Remove.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_RemoveMouseMoved(evt);
            }
        });
        btn_Remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_RemoveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_RemoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_RemoveMouseExited(evt);
            }
        });
        Remove.add(btn_Remove, java.awt.BorderLayout.CENTER);

        MenuIcon.add(Remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 335, 50, 50));

        menu.add(MenuIcon, java.awt.BorderLayout.LINE_START);

        menuhide.setBackground(new java.awt.Color(0, 145, 255));
        menuhide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 102));
        kGradientPanel1.setkGradientFocus(1000);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 145, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_home.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txt_home.setForeground(new java.awt.Color(255, 255, 255));
        txt_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_home.setText("Home");
        kGradientPanel1.add(txt_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 200, 55));

        txt_add.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txt_add.setForeground(new java.awt.Color(255, 255, 255));
        txt_add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_add.setText("Add Employees");
        kGradientPanel1.add(txt_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 200, 55));

        txt_search.setBackground(new java.awt.Color(204, 0, 0));
        txt_search.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txt_search.setForeground(new java.awt.Color(255, 255, 255));
        txt_search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_search.setText("Search");
        kGradientPanel1.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 165, 200, 55));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Edit");
        kGradientPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 200, 55));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Salary");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 275, 200, 55));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Remove");
        kGradientPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 200, 55));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Calendar");
        kGradientPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 200, 55));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Email");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 565, 200, 55));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Setting");
        kGradientPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 200, 55));

        menuhide.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 700));

        menu.add(menuhide, java.awt.BorderLayout.CENTER);

        getContentPane().add(menu, java.awt.BorderLayout.LINE_START);

        dashboardview.setBackground(new java.awt.Color(255, 102, 102));
        dashboardview.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(929, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clock_30px.png"))); // NOI18N

        Time.setFont(new java.awt.Font("Script MT Bold", 0, 14)); // NOI18N
        Time.setText("Time");

        date.setFont(new java.awt.Font("Script MT Bold", 0, 14)); // NOI18N
        date.setText("Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Time)
                .addGap(53, 53, 53)
                .addComponent(date)
                .addContainerGap(939, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Time)
                    .addComponent(date))
                .addContainerGap())
        );

        dashboardview.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        kGradientPanel3.setkEndColor(new java.awt.Color(202, 240, 248));
        kGradientPanel3.setkStartColor(new java.awt.Color(202, 240, 248));
        kGradientPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel9.setkEndColor(new java.awt.Color(255, 204, 102));
        kGradientPanel9.setkGradientFocus(400);
        kGradientPanel9.setkStartColor(new java.awt.Color(255, 51, 0));
        kGradientPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/time_85px.png"))); // NOI18N
        kGradientPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 80, 80));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Hours");
        kGradientPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 186, -1));

        jLabel14.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("80,000");
        kGradientPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, 40));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        kGradientPanel9.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 110, 5));

        jPanel5.setBackground(new java.awt.Color(255, 0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(80, 5));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        kGradientPanel9.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 5));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("52%");
        kGradientPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 30, 20));

        kGradientPanel3.add(kGradientPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 309, 143));

        kGradientPanel10.setkEndColor(new java.awt.Color(255, 153, 255));
        kGradientPanel10.setkStartColor(new java.awt.Color(204, 51, 255));
        kGradientPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add_user_group_man_man_85px.png"))); // NOI18N
        kGradientPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 90, 85));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("New Employees");
        kGradientPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 186, -1));

        jLabel21.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("5,100");
        kGradientPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, 40));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        kGradientPanel10.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 160, 5));

        jPanel7.setBackground(new java.awt.Color(255, 0, 0));
        jPanel7.setPreferredSize(new java.awt.Dimension(80, 5));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        kGradientPanel10.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, 5));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("20%");
        kGradientPanel10.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 30, 20));

        kGradientPanel3.add(kGradientPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 310, 143));

        kGradientPanel15.setkEndColor(new java.awt.Color(153, 255, 153));
        kGradientPanel15.setkGradientFocus(400);
        kGradientPanel15.setkStartColor(new java.awt.Color(0, 153, 0));
        kGradientPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Money Bag Pounds_85px.png"))); // NOI18N
        kGradientPanel15.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 90, 85));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Income");
        kGradientPanel15.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 186, -1));

        jLabel25.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("10,100");
        kGradientPanel15.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, 40));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        kGradientPanel15.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 90, 5));

        jPanel9.setBackground(new java.awt.Color(255, 0, 0));
        jPanel9.setPreferredSize(new java.awt.Dimension(80, 5));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        kGradientPanel15.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, 5));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("65%");
        kGradientPanel15.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 30, 20));

        kGradientPanel3.add(kGradientPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 309, 143));

        qlthongtin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Sex", "Address", "Phone", "Email", "Date of bỉth", "Position"
            }
        ));
        qlthongtin.setFocusable(false);
        qlthongtin.setGridColor(new java.awt.Color(255, 255, 255));
        qlthongtin.setIntercellSpacing(new java.awt.Dimension(0, 0));
        qlthongtin.setRowHeight(25);
        qlthongtin.setSelectionBackground(new java.awt.Color(51, 255, 0));
        qlthongtin.setShowVerticalLines(false);
        qlthongtin.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(qlthongtin);

        kGradientPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 670, 380));

        jButton1.setText("jButton1");
        kGradientPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 70, 120, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        kGradientPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 980, 5));

        jPanel3.setBackground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        kGradientPanel3.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, 5));

        jPanel10.setBackground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        kGradientPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, 5));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        kGradientPanel3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 550, 5));

        jLabel3.setBackground(new java.awt.Color(0, 51, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel3.setText("Home/View");
        kGradientPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nv.png"))); // NOI18N
        kGradientPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 430, 190));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        kGradientPanel3.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 220, 250, 5));

        jLabel4.setBackground(new java.awt.Color(0, 51, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel4.setText("Employees Information");
        kGradientPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 5));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 230, 5));

        jPanel17.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 230, 5));

        jPanel18.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 5));

        jPanel19.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 230, 5));

        jPanel20.setBackground(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 5));

        jLabel11.setBackground(new java.awt.Color(0, 51, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel11.setText("DMC");
        jPanel14.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel21.setBackground(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 210, 5));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 80, 5));

        jLabel27.setBackground(new java.awt.Color(0, 51, 204));
        jLabel27.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel27.setText("HBB");
        jPanel14.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jPanel23.setBackground(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 40, 5));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 120, 5));

        jLabel28.setBackground(new java.awt.Color(0, 51, 204));
        jLabel28.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel28.setText("DBM");
        jPanel14.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jPanel25.setBackground(new java.awt.Color(204, 153, 255));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 130, 5));

        jLabel29.setBackground(new java.awt.Color(0, 51, 204));
        jLabel29.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel29.setText("HAH");
        jPanel14.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jPanel26.setBackground(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 120, 5));

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 90, 5));

        jPanel28.setBackground(new java.awt.Color(204, 153, 255));

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 5));

        jLabel30.setBackground(new java.awt.Color(0, 51, 204));
        jLabel30.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel30.setText("DTC");
        jPanel14.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 180, 5));

        jPanel30.setBackground(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, 5));

        kGradientPanel3.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, 310, 200));

        jLabel8.setBackground(new java.awt.Color(0, 51, 204));
        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel8.setText("Statistics");
        kGradientPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, -1, 20));

        jPanel15.setBackground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        kGradientPanel3.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, 60, 5));

        dashboardview.add(kGradientPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(dashboardview, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1357, 705));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int xx_119, xy_119;
//    public void changecolor (JPanel hover , Color rand){
//        hover.setBackground(rand);        
//    }
     public void clickmenu(JPanel h1, JPanel h2, int numberbool){
        if(numberbool == 1){
            h1.setBackground(new Color(0,145,255));
            h2.setBackground(new Color(0,180,216));
        }
        else{
            h1.setBackground(new Color(0,145,255));
            h2.setBackground(new Color(25, 29, 74));
        }
    }
          public void changeimage(JLabel button, String resourcheimg){
        ImageIcon aimg = new ImageIcon(getClass().getResource(resourcheimg));
        button.setIcon(aimg);
    }
    public void hideshow(JPanel menushowhide, boolean dashboard, JLabel button){
        if(dashboard == true){
            menushowhide.setPreferredSize(new Dimension(50, menushowhide.getHeight()));
            changeimage(button, "/icon/Hamburger Menu_20px.png");
        }
        else{
            menushowhide.setPreferredSize(new Dimension(250, menushowhide.getHeight()));
            changeimage(button, "/icon/back_to_20px.png");
        }
        
    }
        
    private void btn_HidemenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HidemenuMouseClicked
        clickmenu(hideMenu, home, 1);
        // create  void  for  methode hide and show panel menu
        //(tạo khoảng trống cho menu bảng điều khiển ẩn và hiện methode)
        if(a==true){
          hideshow(menu, a, btn_Hidemenu);
          SwingUtilities.updateComponentTreeUI(this);
          //create methode change image
          
          a=false;
        }
        else{
            hideshow(menu, a, btn_Hidemenu);
            SwingUtilities.updateComponentTreeUI(this);
            a=true;
        }
    }//GEN-LAST:event_btn_HidemenuMouseClicked

    private void btn_HidemenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HidemenuMouseEntered
//        changecolor(lineHidemenu, new Color(247,78,105));
    }//GEN-LAST:event_btn_HidemenuMouseEntered

    private void btn_HidemenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HidemenuMouseExited
       //changecolor(lineHidemenu, new Color(0,145,255));
       resetPaneBackground(hideMenu);
       resetPaneBackground(lineHidemenu);
    }//GEN-LAST:event_btn_HidemenuMouseExited

    private void btn_maximus119MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_maximus119MousePressed
        // TODO add your handling code here:
        setColor(btn_maximus119);
        if(this.getExtendedState() != Main.MAXIMIZED_BOTH){
                this.setExtendedState(Main.MAXIMIZED_BOTH);
            }
            else{
                    this.setExtendedState(Main.NORMAL);
            }  
    }//GEN-LAST:event_btn_maximus119MousePressed

    private void btn_close119MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_close119MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_close119MousePressed

    private void btn_mini119MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mini119MousePressed
        // TODO add your handling code here:
        Main.this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btn_mini119MousePressed

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        // TODO add your handling code here:
        xx_119 = evt.getX();
        xy_119 = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx_119, y-xy_119);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2 && !evt.isConsumed()){
            if(Main.this.getExtendedState() == MAXIMIZED_BOTH){
                Main.this.setExtendedState(JFrame.NORMAL);
            }
            else{
                Main.this.setExtendedState(WIDTH);
            }
        }
    }//GEN-LAST:event_HeaderMouseClicked

    private void btn_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseClicked
        AddForm fm = new AddForm();
        fm.setVisible(true);
    }//GEN-LAST:event_btn_addMouseClicked

    private void btn_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseEntered
        // TODO add your handling code here:
//        changecolor(lineadd, new Color(247,78,105));
    }//GEN-LAST:event_btn_addMouseEntered

    private void btn_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseExited
        // TODO add your handling code here:
       resetPaneBackground(add);
       resetPaneBackground(lineadd);
    }//GEN-LAST:event_btn_addMouseExited

    private void btn_SettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SettingMouseClicked
        // TODO add your handling code here:
//        clickmenu(setting,Email, 1);
    }//GEN-LAST:event_btn_SettingMouseClicked

    private void btn_SettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SettingMouseEntered
        // TODO add your handling code here:
//         changecolor(lineSetting, new Color(247,78,105));
    }//GEN-LAST:event_btn_SettingMouseEntered

    private void btn_SettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SettingMouseExited
        resetPaneBackground(setting);
       resetPaneBackground(lineSetting);
    }//GEN-LAST:event_btn_SettingMouseExited

    private void btn_EmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmailMouseClicked
        // TODO add your handling code here:
//        clickmenu(Email,Calender, 1);
    }//GEN-LAST:event_btn_EmailMouseClicked

    private void btn_EmailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmailMouseEntered
        // TODO add your handling code here:
//         changecolor(lineEmail, new Color(247,78,105));
    }//GEN-LAST:event_btn_EmailMouseEntered

    private void btn_EmailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmailMouseExited
        resetPaneBackground(Email);
       resetPaneBackground(lineEmail);
    }//GEN-LAST:event_btn_EmailMouseExited

    private void btn_CalendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CalendarMouseClicked
        // TODO add your handling code here:
//        clickmenu(Calender,Remove, 1);
    }//GEN-LAST:event_btn_CalendarMouseClicked

    private void btn_CalendarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CalendarMouseEntered
        // TODO add your handling code here:
//         changecolor(lineCalendar, new Color(247,78,105));
    }//GEN-LAST:event_btn_CalendarMouseEntered

    private void btn_CalendarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CalendarMouseExited
        resetPaneBackground(Calender);
       resetPaneBackground(lineCalendar);
    }//GEN-LAST:event_btn_CalendarMouseExited

    private void btn_SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SearchMouseClicked
        // TODO add your handling code here:
//        clickmenu(Search,add, 1);
    }//GEN-LAST:event_btn_SearchMouseClicked

    private void btn_SearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SearchMouseEntered
        // TODO add your handling code here:
//        changecolor(lineSearch, new Color(247,78,105));
    }//GEN-LAST:event_btn_SearchMouseEntered

    private void btn_SearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SearchMouseExited
        // TODO add your handling code here:
        resetPaneBackground(Search);
       resetPaneBackground(lineSearch);
    }//GEN-LAST:event_btn_SearchMouseExited

    private void btn_EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditMouseClicked
        UpdateForm fm = new UpdateForm();
        fm.setVisible(true);
    }//GEN-LAST:event_btn_EditMouseClicked

    private void btn_EditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditMouseEntered
        // TODO add your handling code here:
//        changecolor(lineEdit, new Color(247,78,105));
    }//GEN-LAST:event_btn_EditMouseEntered

    private void btn_EditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditMouseExited
        resetPaneBackground(Edit);
       resetPaneBackground(lineEdit);
    }//GEN-LAST:event_btn_EditMouseExited

    private void btn_SalaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SalaryMouseClicked
        DieuChinhLuong fm = new DieuChinhLuong();
        fm.setVisible(true);
    }//GEN-LAST:event_btn_SalaryMouseClicked

    private void btn_SalaryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SalaryMouseEntered
        // TODO add your handling code here:
//        changecolor(linerSalary, new Color(247,78,105));
    }//GEN-LAST:event_btn_SalaryMouseEntered

    private void btn_SalaryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SalaryMouseExited
        resetPaneBackground(Salary);
       resetPaneBackground(linerSalary);
    }//GEN-LAST:event_btn_SalaryMouseExited

    private void btn_RemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RemoveMouseClicked
        // TODO add your handling code here:
//        clickmenu(Remove,Salary, 1);
    }//GEN-LAST:event_btn_RemoveMouseClicked

    private void btn_RemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RemoveMouseEntered
        // TODO add your handling code here:
//        changecolor(lineRemove, new Color(247,78,105));
    }//GEN-LAST:event_btn_RemoveMouseEntered

    private void btn_RemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RemoveMouseExited
        resetPaneBackground(Remove);
       resetPaneBackground(lineRemove);
    }//GEN-LAST:event_btn_RemoveMouseExited

    private void btn_HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseExited
       resetPaneBackground(home);
       resetPaneBackground(linehome);
    }//GEN-LAST:event_btn_HomeMouseExited

    private void btn_HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseEntered
        //changecolor(linehome, new Color(247,78,105));
    }//GEN-LAST:event_btn_HomeMouseEntered

    private void btn_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseClicked
       // clickmenu(home,hideMenu, 1);
    }//GEN-LAST:event_btn_HomeMouseClicked

    private void hideMenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMenuMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_hideMenuMouseMoved

    private void hideMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMenuMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_hideMenuMouseExited

    private void homeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_homeMouseMoved

    private void btn_HidemenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HidemenuMouseMoved
        // TODO add your handling code here:
        setPaneBackground(hideMenu);
        changeColor(lineHidemenu, new Color(255,0,43));
    }//GEN-LAST:event_btn_HidemenuMouseMoved

    private void btn_HomeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseMoved
        // TODO add your handling code here:
        setPaneBackground(home);
        changeColor(linehome, new Color(255,0,43));
    }//GEN-LAST:event_btn_HomeMouseMoved

    private void btn_addMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseMoved
        // TODO add your handling code here:
        setPaneBackground(add);
        changeColor(lineadd, new Color(255,0,43));
    }//GEN-LAST:event_btn_addMouseMoved

    private void btn_SearchMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SearchMouseMoved
        // TODO add your handling code here:
        setPaneBackground(Search);
        changeColor(lineSearch, new Color(255,0,43));
    }//GEN-LAST:event_btn_SearchMouseMoved

    private void btn_EditMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EditMouseMoved
        // TODO add your handling code here:
        setPaneBackground(Edit);
        changeColor(lineEdit, new Color(255,0,43));
    }//GEN-LAST:event_btn_EditMouseMoved

    private void btn_SalaryMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SalaryMouseMoved
        // TODO add your handling code here:
        setPaneBackground(Salary);
        changeColor(linerSalary, new Color(255,0,43));
    }//GEN-LAST:event_btn_SalaryMouseMoved

    private void btn_RemoveMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RemoveMouseMoved
        // TODO add your handling code here:
        setPaneBackground(Remove);
        changeColor(lineRemove, new Color(255,0,43));
    }//GEN-LAST:event_btn_RemoveMouseMoved

    private void btn_CalendarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CalendarMouseMoved
        // TODO add your handling code here:
        setPaneBackground(Calender);
        changeColor(lineCalendar, new Color(255,0,43));
    }//GEN-LAST:event_btn_CalendarMouseMoved

    private void btn_EmailMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmailMouseMoved
        // TODO add your handling code here:
        setPaneBackground(Email);
        changeColor(lineEmail, new Color(255,0,43));
    }//GEN-LAST:event_btn_EmailMouseMoved

    private void btn_SettingMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SettingMouseMoved
        // TODO add your handling code here:
        setPaneBackground(setting);
        changeColor(lineSetting, new Color(255,0,43));
    }//GEN-LAST:event_btn_SettingMouseMoved

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addMouseClicked
    
    private void setColor(JLabel pane){
        pane.setBackground(new Color(204,0,0));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    private void setPaneBackground(JPanel jp){
        jp.setBackground(new Color(0,180,216));
    }
    private void resetPaneBackground(JPanel jp){
        jp.setBackground(new Color(0,145,255));
    }
    private void changeColor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Calender;
    private javax.swing.JPanel Edit;
    private javax.swing.JPanel Email;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel MenuIcon;
    private javax.swing.JPanel Remove;
    private javax.swing.JPanel Salary;
    private javax.swing.JPanel Search;
    private javax.swing.JLabel Time;
    private javax.swing.JPanel add;
    private javax.swing.JLabel btn_Calendar;
    private javax.swing.JLabel btn_Edit;
    private javax.swing.JLabel btn_Email;
    private javax.swing.JLabel btn_Hidemenu;
    private javax.swing.JLabel btn_Home;
    private javax.swing.JLabel btn_Remove;
    private javax.swing.JLabel btn_Salary;
    private javax.swing.JLabel btn_Search;
    private javax.swing.JLabel btn_Setting;
    private javax.swing.JLabel btn_add;
    private javax.swing.JLabel btn_close119;
    private javax.swing.JLabel btn_maximus119;
    private javax.swing.JLabel btn_mini119;
    private javax.swing.JPanel dashboardview;
    private javax.swing.JLabel date;
    private javax.swing.JPanel hideMenu;
    private javax.swing.JPanel home;
    private javax.swing.JLabel icontitle119;
    private javax.swing.JPanel iocnMinMaxClose;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel10;
    private keeptoo.KGradientPanel kGradientPanel15;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel9;
    private javax.swing.JPanel lineCalendar;
    private javax.swing.JPanel lineEdit;
    private javax.swing.JPanel lineEmail;
    private javax.swing.JPanel lineHidemenu;
    private javax.swing.JPanel lineRemove;
    private javax.swing.JPanel lineSearch;
    private javax.swing.JPanel lineSetting;
    private javax.swing.JPanel lineadd;
    private javax.swing.JPanel linehome;
    private javax.swing.JPanel linerSalary;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuhide;
    private javax.swing.JTable qlthongtin;
    private javax.swing.JPanel setting;
    private javax.swing.JLabel title119;
    private javax.swing.JPanel title_header119;
    private javax.swing.JLabel txt_add;
    private javax.swing.JLabel txt_home;
    private javax.swing.JLabel txt_search;
    // End of variables declaration//GEN-END:variables
    private void showTable() {
        ql =new NhanVienDAO().getAllUsers();
        model.setRowCount(0);
        for(nhanVien qly : ql){
            model.addRow(new Object[]{
                qly.getID(), qly.getName(), qly.getSex(), qly.getAddress(), qly.getPhone(), qly.getEmail(), qly.getDateOfBirth(), qly.getPosition()
            });
        }
    }
}
